// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szbqmovulttttcuykyee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6YnFtb3Z1bHR0dHRjdXlreWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDU2MjIsImV4cCI6MjA2MzQ4MTYyMn0.M6f83mdnRkzOLiLR0FFu9k_mMuT0Njqvm5KfOm8Umxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);